### ISSUE TITLE
Chern number in non-square lattices

### ISSUE THREAD

**Issue by BArt22023** [actyner/BerryEasy#1]
Hi, I have tried BerryEasy. He looks pretty friendly.

I have a doubt if it is possible to extend the calculation of the Chern number to other types of lattices, such as for the Haldane model (honeycomb lattice). In that case, how should the calc_chern function be modified?

thanks.

**Comment by actyner** [comment]
Calculation of Chern number in non-square lattice is supported in this version without modification to the calc_chern function. Upon defining the Haldane model in the PyBinding formalism the Chern number can be computed via hybrid Wannier centers using the exact same code used in the tutorial for a square lattice.  

A separate example of computing topological invariants in a non-square lattice is given in the context of Wannier tight-binding models as the Z2 index is computed for bilayer-bismuth which supports three-fold symmetry (i.e. a non-square lattice).

Hope that helps!

**Comment by BArt22023** [comment]
Thank you very much, it works fine. Another question, in pybinding it is somewhat difficult to evaluate the wave function for specific k points within the first zone or to project the wave function to a certain sublattice. Can this be done in Berryeasy?

**Comment by BArt22023** [comment]
thank so much
